# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d9f2874448e439ea80ba11b10e72b3257c7d93fe41b948f8c1d03d9af8ac8c9dabf857ee97dadd052f473c88656fc54416f795a9447431bc000cd80139888b81

test:
  secret_key_base: 76c01ec57a4fe164736b9866e4643c75f800ebe173b5dd5df01813e9ca2e5e166190406645a510112c3507b4271f3141980e60cfcbfb76c1d1a141b529e460c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
